version: '3'
services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: Dockerfile-http
    ports:
      - "8000:8000"
